name: Black check

on:
  push:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name: Install black formatter
        run: pip install black

      - name: Check code
        run: black . --check --color --diff
