name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  black-formatter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name: Install black formatter
        run: pip install black

      - name: Check code
        run: black . --check --color --diff

  deploy:
    runs-on: ubuntu-latest
    needs: black

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DEV Server
        env:
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
            DOCKER_COMPOSE_FILE: "docker-compose.yaml"
        run: bash deploy.sh
